### ISSUE TITLE
v1.1.1-191 broke autogeneration of i18n.dart

### ISSUE THREAD

**Issue by KorbinianMossandl** [long1eu/flutter_i18n#103]
i just upgraded to the latest version and now the i18n file won't update if i make changes to my strings_en.arb

**Comment by noordawod** [comment]
There has been a new feature with the release of v1.1.0, could you please read the README and tell me if this fits your usecase?

https://github.com/long1eu/flutter_i18n#3-turning-off-the-plugin-per-project

**Comment by KorbinianMossandl** [comment]
sadly not. i am using the plugin on a flutter project. 
Even setting it to enabled did not do the trick. for now only downgrading resolves the issue.

**Comment by noordawod** [comment]
This is very strange.

The plugin detects the existance of Flutter in pubspec.yaml, so could you possibly attach it here (you can leave sensitive info out)?

**Comment by noordawod** [comment]
Also, what's the highest version number that works for you?

**Comment by KorbinianMossandl** [comment]
i just went back to v1.0.6-191 since this was the version i used before the upgrade.

```
name: XXX
description: XXX

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  intl: ^0.15.8
  cupertino_icons: ^0.1.2
  json_annotation: ^2.3.0
  dio: ^2.1.0
  json_serializable: ^3.0.0
  cookie_jar: ^1.0.0
  sembast: ^1.15.4
  path_provider: ^1.1.0
  encrypt: ^3.1.0
  background_fetch: ^0.2.0
  sentry: ^2.2.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.13.1
  path_drawing: ^0.4.1
  bubble_tab_indicator: ^0.1.4
  google_maps_flutter: ^0.5.21
  url_launcher: ^5.1.2
  permission_handler: ^3.2.0
  path: ^1.6.2
  pdf_render: ^0.56.0
  webview_flutter: ^0.3.14
  camera: ^0.5.4+2
  file_picker: ^1.4.2

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: ^1.6.3
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
   - res/assets/icons/
   - res/assets/logos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
