### ISSUE TITLE
Reload manually generated/i18n.dart

### ISSUE THREAD

**Issue by EArminjon** [long1eu/flutter_i18n#121]
Hello,

The plugin automatically reload i18n.dart on android.studio and inteljidea.
In the case where some developers do not use both of them, how generate/reload manually this file ? If it required java, could you provide a little script to do it ?

**Comment by EArminjon** [comment]
Find solution : 
https://github.com/long1eu/flutter_i18n/tree/master/flutter_l10n

Add this in pubspec.yaml

```yaml
l10n_generator:
    git:
      url: https://github.com/long1eu/flutter_i18n
      path: flutter_l10n/
```

Commande to run generator :
```bash
flutter packages pub run l10n_generator:main -o lib/generated
```

But their is an other problem (About string containing "\n"), will create an other issue.
